name: Build Tower Detective

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install dependencies
        run: npm install

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Make Gradle executable
        working-directory: android
        run: chmod +x gradlew

      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Build Release AAB
        working-directory: android
        run: ./gradlew bundleRelease

      - name: Show generated files
        run: |
          echo "========== APK =========="
          find android/app/build/outputs/apk -type f -name "*.apk" -print

          echo "========== AAB =========="
          find android/app/build/outputs/bundle -type f -name "*.aab" -print

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Tower-Detective-APK
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: Tower-Detective-AAB
          path: android/app/build/outputs/bundle/release/*.aab
          if-no-files-found: error
